### ISSUE TITLE
提取PDF文本

### ISSUE THREAD

**Issue by daniel-007** [hhrutter/pdfcpu#13]
请问如何提取PDF文件的内容？ExtractContent方法是dumps "PDF source"？那么如何提取文本格式的内容呢？谢谢！

**Comment by hhrutter** [comment]
If you could raise this issue in English I am able to help.

**Comment by daniel-007** [comment]
Sorry. So how to extract the contents of the text format? Thank you!

**Comment by hhrutter** [comment]
`Extract Content` gives you a content streams content in PDF syntax.
What you need is `Extract Text` and this is not supported as of now.

**Comment by daniel-007** [comment]
Thank you very much, I am looking forward to it.
