### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by nottest** [hhrutter/pdfcpu#14]
Does this library supports UTF-8? Looking for pdf generator which supports Chinese characters.

Thanks & Rgds,
Nanthini

**Comment by hhrutter** [comment]
Hi there,
pdfcpu ist not a pdf generator.
Its focus is to process existing pdfs.

It supports UTF-8 but I haven't tested with a Chinese PDF.
This is a great opportunity. :)
Can you send me a sample PDF in Chinese that I can integrate in the testsuite?

Thank you so much!
