### ISSUE TITLE
Merge files command order

### ISSUE THREAD

**Issue by juanchorossi** [hhrutter/pdfcpu#16]
Hi there @hhrutter, great project!

I'm using the merge command, expecting a final PDF with the exact input order, but the result PDF has a random order.
Am I using the command incorrectly? Should I use another feature? I need to create an output PDF with multiple PDFs in a precise given order.

Thanks in advance

`
ouputFile := fmt.Sprintf("output/result_%s.pdf", time.Now().Format("20060102-1504"))
pdfcpu.Merge(pdfMergeOrder, ouputFile, types.NewDefaultConfiguration())
`

The source array:
```
source_pdfs/7688393.pdf
source_pdfs/22139401.pdf
source_pdfs/32340834.pdf
source_pdfs/63906135.pdf
source_pdfs/64324713.pdf
source_pdfs/67541469.pdf
source_pdfs/90838299.pdf
source_pdfs/109121616.pdf
source_pdfs/109566867.pdf
source_pdfs/121581951.pdf
source_pdfs/138967698.pdf
source_pdfs/180903826.pdf
source_pdfs/258023538.pdf
```

The log, as you may see sorting is not being maintained 
```
merging in source_pdfs/121581951.pdf
merging in source_pdfs/138967698.pdf
merging in source_pdfs/258023538.pdf
merging in source_pdfs/63906135.pdf
merging in source_pdfs/64324713.pdf
merging in source_pdfs/90838299.pdf
merging in source_pdfs/109566867.pdf
merging in source_pdfs/180903826.pdf
merging in source_pdfs/22139401.pdf
merging in source_pdfs/32340834.pdf
merging in source_pdfs/67541469.pdf
merging in source_pdfs/109121616.pdf
```

**Comment by hhrutter** [comment]
This should have been fixed with the latest commit.

**Comment by juanchorossi** [comment]
Great! Thanks
