### ISSUE TITLE
Add PageCount example

### ISSUE THREAD

**Issue by jayminkapish** [hhrutter/pdfcpu#17]
This is a great package. Thanks for building this.

I have a quick request: is it possible for you to add an example of how to get PageCount for a given PDF?

**Comment by hhrutter** [comment]
see api.go:

ctx, durRead, durVal, durOpt, err := readValidateAndOptimize(fileIn, config, fromStart)

ctx.PageCount

Let me know if you have any further questions.

**Comment by hhrutter** [comment]
see v0.1.10 for a testcase for this.
