### ISSUE TITLE
recent change causes go get error from upspin

### ISSUE THREAD

**Issue by jadefox10200** [hhrutter/pdfcpu#18]
I had to recently move my project to a new machine so the project could go live. I therefore had to run go get on that new machine for pdfcpu. In extract.go you use the following package: 

"github.com/hhrutter/upspin/errors"

When running `go get github.com/hhrutter/pdfcpu` I get the following error:

`package upspin.io/log: unrecognized import path "upspin.io/log" (https fetch: Get https://upspin.io/log?go-get=1: proxyconnect tcp: tls: oversized record received with length 20527)
package upspin.io/upspin: unrecognized import path "upspin.io/upspin" (https fetch: Get https://upspin.io/upspin?go-get=1: proxyconnect tcp: tls: oversized record received with length 20527)`

This should be reverted to the follwing package as is it is only used in one place in that file and all other files of pdfcpu use this package:

"github.com/pkg/errors"

**Comment by hhrutter** [comment]
Thx so much for reporting @jadefox10200 
This is a bug that slipped in with the latest release! 
I am gonna push a new release over the weekend with this fix.

**Comment by hhrutter** [comment]
fixed with v0.1.10
