### ISSUE TITLE
Error when merging file

### ISSUE THREAD

**Issue by AndrewGrachov** [hhrutter/pdfcpu#19]
Having error, when trying to merge pdf files into 1 

dereferenceObject: problem dereferencing object 7: parse: duplicate key
```
  _, err = pdfcpu.Process(pdfcpu.MergeCommand(filePaths, baseDir+".pdf", pdfcputypes.NewDefaultConfiguration()))
```

UPD: Pdf files were generated by electron

**Comment by hhrutter** [comment]
Please run pdfcpu with -v and post the stacktrace.
Thank you so much for reporting this!

**Comment by hhrutter** [comment]
```Duplicate key``` is a parsing error.
Please check with pdfcpu if your source files are valid:
```pdfcpu validate a.pdf```
If they are not there is no point in trying to merge them.
I am closing this for now.
