### ISSUE TITLE
Adding Documentation

### ISSUE THREAD

**Issue by KingAkeem** [hhrutter/pdfcpu#20]
I was looking through the code base and I'd like to add more documentation for anyone who'd like to contribute in the future. Plus, I think it'd give me a much better understanding of the code base in general.

**Comment by KingAkeem** [comment]
I was thinking of expanding on the source code doc, but I didn't see the godoc and PDF specification. That actually seems sufficient. I'd like to contribute to the repository, do you have any suggestions?

**Comment by hhrutter** [comment]
Although I appreciate your intention of helping out right now is not a good time for contributions
other than bugfixes as I am working on pdfcpu's code organization/structure which I am not happy about.
Merging in PRs would be a pain in this situation.
The next release hopefully will have an adequate package structure and then I can also open `help wanted` issues so please bear with me.
