### ISSUE TITLE
.pdf extension requirement should be case insensitive

### ISSUE THREAD

**Issue by coreyog** [hhrutter/pdfcpu#21]
I have a pdf with the file extension ".PDF" and was given the output that the file `needs extension ".pdf".` It's a simple work around to make it work, but the file is properly a pdf so it would be nice if the tool "just worked."

**Comment by hhrutter** [comment]
Thanks for reporting this. Will be fixed in the next release.

**Comment by hhrutter** [comment]
fixed by version 0.1.12
