### ISSUE TITLE
Getting the Page Count

### ISSUE THREAD

**Issue by tcurdt** [hhrutter/pdfcpu#28]
I am struggling a little with the API. All feels quite low level.
My goal is to just figure out the number of pages of a PDF.

Got some pointers?

Would also make a nice little example for the API usage.

**Comment by hhrutter** [comment]
There is a test that covers getting the page count at:
pkg/api/process_test.go: func TestGetPageCount

OK, I am working on a new release and will turn this into an example so it shows up in godoc.

**Comment by tcurdt** [comment]
Perfect! Thanks!

**Comment by fcce** [comment]
https://github.com/pdfcpu/pdfcpu/blob/05bd28049f95fd1b7226399522a9da6db4d4c79c/pkg/api/page.go#L208
