### ISSUE TITLE
Get rid of excessive logging

### ISSUE THREAD

**Issue by tadvi** [hhrutter/pdfcpu#3]
Libraries and source code has excessive logging interleaved with code that does main work.
This makes reading source code harder.

Lines like:
logInfoValidate.Println("*** validateShadingDictCommonEntries end ***")

Go standard library should be inspiration for this. It has no excessive logging inside library code.
Please get rid of logging inside the library.

**Comment by hhrutter** [comment]
Thanks, I am aware but I still need all of this for debugging. Still at 0.0.x. I will mark the next version as prerelease.
