### ISSUE TITLE
converting to PDF/A

### ISSUE THREAD

**Issue by tcurdt** [hhrutter/pdfcpu#30]
It would be great if `pdfcpu` could be used to convert to PDF/A

https://en.wikipedia.org/wiki/PDF/A

**Comment by hhrutter** [comment]
I haven't had a chance to take a look at PDFA because PDF 1.7 is keeping me busy
:)

In a nutshell what would be the benefit in having such a feature (assuming this can actually be done)?
Any good usecase?

**Comment by tcurdt** [comment]
PDFA is a ISO standard for long-term archival. For public administration and other areas it's apparently a requirement.

> Why PDF/A and not just PDF?
Put in the simplest possible terms, PDF/A is a PDF which forbids certain functions which could hinder long-term archiving. PDF/A also demands that the file meet certain requirements which guarantee reliable reproduction.

> For example, files must not be encrypted with a password, as all content must always be fully available. Embedded video and audio data are also prohibited: PDF/A consciously avoids anything that requires external software for display or playback. JavaScript and certain actions are also forbidden, as executing them could potentially alter the PDF.

> PDF/A also places higher demands on the information it contains. All required fonts (or at least all glyphs for the specific characters used) must be embedded within the PDF. To ensure a uniform colour appearance on a variety of platforms and devices, colour information must be given in a platform-independent format using ICC colour profiles. The software must also use the XMP format for metadata (which is used to store the data identifying the file as a PDF/A, for example).

> PDF/A also sets technical limits: for example, the page size is limited to an edge length of either 5.08 metres (PDF/A-1) or up to 381 kilometres (PDF/A-2 and PDF/A-3).

(from https://www.pdfa.org/pdfa-facts-%C2%96-an-introduction-to-the-standard/ )

**Comment by hhrutter** [comment]
Fair enough.
I don't think a functionality to turn a PDF into PFD/A makes much sense,
because one had possibly to get right rid of content that's not allowed in
PDF/A.
Still, validating against the PDF/A spec is possible but that's out of
scope for pdfcpu which aims to implement ISO-32000.
Also 99% of the PDF content you come across on a daily basis is PDF.

**Comment by tcurdt** [comment]
> I don't think a functionality to turn a PDF into PFD/A makes much sense,

Why is that? Stripping out or inlining those bits seems to be common practice.
It's just sad one has to use GhostScript, Adobe or something else for it.
This would allow for some better tooling based on `pdfcpu`

> Also 99% of the PDF content you come across on a daily basis is PDF.

Well, a PDF/A is just a more restrictive PDF.
I wouldn't even know if the PDFs I am getting are PDF/A or not.

Anyway - too bad. I think it would be a nice fit.
But you are the project owner :)

**Comment by hhrutter** [comment]
Well, if Adobe already has such a feature then it certainly would be
possible to add such a feature to pdfcpu as well.

It's just that implementing the PDF/A conversion takes time and I already
have a list of features that I like to implement and this list is already
keeping me busy more than I want to.
