### ISSUE TITLE
producer is empty

### ISSUE THREAD

**Issue by tcurdt** [hhrutter/pdfcpu#31]
I have PDF starting like this
```
%PDF-1.4
%<B7><BE><AD><AA>
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj
2 0 obj
<<
/Type /Pages
/Kids [ 6 0 R ]
/Count 1
>>
endobj
3 0 obj
<<
/Producer (Haru Free PDF Library 2.3.0RC2)
>>
endobj
4 0 obj
<<
/Length 5 0 R
/Type /XObject
/Subtype /Image
/Height 1461
/Width 1037
/ColorSpace /DeviceRGB
/BitsPerComponent 8
/Filter [ /DCTDecode ]
```
And I was trying to read some of the header information like this:

```
	config := pdfcpu.NewDefaultConfiguration()

	ctx, err := pdfcpu.ReadPDFFile(path, config)
	if err != nil {
		return errors.Wrapf(err, "failed to read file")
	}

	// err = pdfcpu.ValidateXRefTable(ctx.XRefTable)
	// if err != nil {
	// 	return errors.Wrapf(err, "failed to validate xref table")
	// }

	fmt.Printf("version: %s\n", ctx.XRefTable.VersionString())
	fmt.Printf("author: %s\n", ctx.XRefTable.Author)
	fmt.Printf("creator: %s\n", ctx.XRefTable.Creator)
	fmt.Printf("producer: %s\n", ctx.XRefTable.Producer)
```

But no matter whether I validate first or not the `Producer` field is empty.
I would have expected it to be `Haru Free PDF Library 2.3.0RC2`.
What am I missing?

**Comment by hhrutter** [comment]
First of all any object may be present multiple times (with same obj#) in a PDF because there may be nested xreftables, secondly Creator, Producer and so forth are part of the info dict, but only the infodict thats referenced in the trailer info. Send me the file and I can verify that for you.

**Comment by hhrutter** [comment]
no further action. I am closing this.
