### ISSUE TITLE
AcroForms support

### ISSUE THREAD

**Issue by mbinette** [hhrutter/pdfcpu#35]
There is a reference to AcroForms in the test PDF code but is their a way for me to populate a fillable PDF with data programmatically? I already have a bunch of fillable PDFs but was hoping to use Go and not something like Apache PDFBox (Java) to accomplish this. I also can't use something like PDFtk because of licensing.

**Comment by hhrutter** [comment]
Although I cannot give you a specific timeline AcroForm templating/filling and is an upcoming feature of pdfcpu. Please check back. 

As far as licensing `pdfcpu` is moving to Apache 2.0.

Please star `pdfcpu` if you like it.
Thank you.
