### ISSUE TITLE
How to extract text data from PDF?

### ISSUE THREAD

**Issue by ekanna** [hhrutter/pdfcpu#37]
I am using below command

```
pdfcpu extract -mode=content inputFile.pdf outputDir
```

But i don't know how to convert this PDF-Source into text data.

Can you through some light onto this?

Thanks

**Comment by hhrutter** [comment]
Hi!

The extract mode `content` only gives you the page content in PDF Syntax.
Text extraction will be available in one of the next releases.

**Comment by ekanna** [comment]
Thank you.

**Comment by sannihith1995** [comment]
Hi,
Even I'm excited about this. Waiting for the update.

**Comment by hhrutter** [comment]
This is postponed until further notice because of the complexity and amount of work involved.
