### ISSUE TITLE
Using pdfcpu API from []byte

### ISSUE THREAD

**Issue by protheusfr** [hhrutter/pdfcpu#44]
Hello,

It seems all API is oriented to read and write content from and to file (os.file).
Is there a simple way to use it from and to []byte (in order to include them in back of an HTTP API for ex.) ?

**Comment by hhrutter** [comment]
Not at the moment unfortunately. I am working on io.Reader/Writer access but it's tricky because I want to maintain consistency across the API.

There is somebody who made a fork work with Afero though, see PR #33.

**Comment by protheusfr** [comment]
I’ve started of fork for that but effectively, this seems tricky.
The os.file is deeply used into calls…

I’ll let you know

**Comment by hhrutter** [comment]
Sure, let me know how that goes.

**Comment by wv0m56** [comment]
@hhrutter,

Do you have anything against adding another function to the API, say:
`ReadStream(r io.Reader, config *Configuration) (*PDFContext, error) {...}`

That way, users with []byte to process can simply pass bytes.NewReader(b) into r.

I can do a quick PR if you're ok with this.

**Comment by wv0m56** [comment]
I spoke too soon, adding the API would require rigging ReadContext. Which is doable, but not "quick".

**Comment by hhrutter** [comment]
Exactly, this is no issue calling for a quick PR.

**Comment by wv0m56** [comment]
We could make ReadContext and WriteContext interfaces, but every time a member field is accessed, it will become get() and set().
```
	if ctx.Read.UsingXRefStreams {
		logStr = append(logStr, "using xref streams\n")
	}
```
becomes 
```
	if ctx.Read.GetUsingXRefStreams() {
		logStr = append(logStr, "using xref streams\n")
	}
```

We also need the required attributes of a file (name, size, etc) to accompany the io.Reader.

Code pollution I know. Go needs generics.

**Comment by hhrutter** [comment]
Hopefully fixed with v0.1.18.
Let me know if you run into issues!

**Comment by bobheadxi** [comment]
Hi @hhrutter , it doesn't seem apparent to me how this issue was fixed - is there an example somewhere for pdfcpu usage with `[]byte`? thanks!

**Comment by bobheadxi** [comment]
I found it, thanks!

For future visitors to this thread:
- [ReadContext in godoc](https://godoc.org/github.com/hhrutter/pdfcpu/pkg/api#ReadContext)
- [ReadContext in api/process_test.go](https://github.com/hhrutter/pdfcpu/blob/master/pkg/api/process_test.go#L86)

**Comment by hhrutter** [comment]
My bad. I know documentation is lacking. I am working that. Thanks for using pdfcpu :greenheart

**Comment by lgonzalez-silen** [comment]
Pity. Makes it hard to use the api without slowing things down and cluttering by writing temp files in order to use. Looking forward to improvements @hhrutter ! Thanks for building.

**Comment by hhrutter** [comment]
Please use the latest and greatest which features strong Reader/Writer support and let me know if you have any questions. Once we are past that I am happy to address any justifiable complaint via a new issue. This one is closed. 
![IMG_20190727_113144](https://user-images.githubusercontent.com/11322155/62016347-8359ed00-b166-11e9-8caf-133796359bbe.jpg)
s. This issue is closed.

**Comment by lgonzalez-silen** [comment]
Ok. Will look some more and then open an issue. Maybe I missed something? I used Merge, which uses ReadSeekerCloser, which is a pain to use unless you use os.File. And also used ImportImages, which did not take Reader images but instead took filenames in the filesystem. I will open an issue for each. Thanks!

**Comment by wv0m56** [comment]
@lgonzalez-silen 
You can create a ReadSeekerCloser from []byte using the standard library.
Pseudocode:
```
type BytesReadSeekCloser struct{ *bytes.Reader }
func (brsc *BytesReadSeekCloser) Close() error { return nil }
```
If what you have is any arbitrary Reader, then unfortunately you have to load the whole thing to memory first (if you want to do it the above way).

Also, [ImportImages](https://godoc.org/github.com/hhrutter/pdfcpu/pkg/api#ImportImages) takes a ReadSeeker, which can be created using bytes.NewReader(b).
