### ISSUE TITLE
PDF Validation

### ISSUE THREAD

**Issue by gedw99** [hhrutter/pdfcpu#48]
I am not a PDF expert at all and would appreciate to know people's opinions about how well pdfCPU supports PDF/A validation.
I ask this because i have been taksed with setting up a Digital Preservation system for long term storage of documents and photos.

Background is here:
http://openpreservation.org/news/verapdf-announced-as-finalist-for-the-digital-preservation-awards-2018/

http://verapdf.org/home/

https://github.com/verapdf
Its hilarious that the tool requires a Java Virtual Machine. Not very digtial future proof :)

**Comment by hhrutter** [comment]
Hello!
Right now pdfcpu validates against PDF 32000-1:2008 (PDF 1.7).
PDF/A validation is a known feature request (See #34) and in the works!
