### ISSUE TITLE
PDF stamping: Is it possible with current merge functions?

### ISSUE THREAD

**Issue by dtrehas** [hhrutter/pdfcpu#5]
Thank you for your awesome project! Hurray! I was waiting something like that for loooong time

Can you verify if I could stamp a pdf file with an another pdf file using the merging facility? 

Cheers! Dimitris

**Comment by hhrutter** [comment]
It really depends on what you mean by stamping. 
I do not understand what's stamping got to do with merging of two files.
When I hear PDF stamping I am thinking more about watermarking pages.
Please propose your exact requirements.

A content transformer for sweeping over pages and page content sections is being worked on. 
Something like this can also be used for watermarking a file.

**Comment by dtrehas** [comment]
You are write, I mean watermarking pages. I used a term that is coming from the "Adobe Acrobat" world.

Again thanks for your time.

**Comment by kardianos** [comment]
As a variant of this issue, I'd like to take three documents: header, footer, and content and merge them together into a single PDF. I need to figure out an alternative to wkhtmltopdf and chrome headless + a feature like that would enable me to make that.

**Comment by hhrutter** [comment]
I think this is more a usecase for https://github.com/jung-kurt/gofpdf.
pdfcpu is meant to be a processor rather than a generator
but stamping is still a feature to come.

**Comment by dtrehas** [comment]
Dear Mr Hrutter,
Can you describe in general what is the procedure about  making an overlay to a pdf file? 
Thank you in advance :)

**Comment by hhrutter** [comment]
There is no better source than the PDF specification document.

**Comment by hhrutter** [comment]
v0.1.15 comes with support for watermarking/stamping PDFs with text or images.

**Comment by dtrehas** [comment]
Excellent! Thank you spending time for this issue!

**Comment by dtrehas** [comment]
Is it possible to stamp/watermark a pdf file with another pdf file like adobe acrobat?

**Comment by hhrutter** [comment]
not yet but coming up

**Comment by hhrutter** [comment]
fixed with v0.1.18
