### ISSUE TITLE
Specify the importance of calling pdfcpu.OptimizeXRefTable before dealing with fonts.

### ISSUE THREAD

**Issue by miyoyo** [hhrutter/pdfcpu#50]
/

**Comment by hhrutter** [comment]
Hey, you must be the first to be dealing with fonts with pdfcpu.
What's your usecase?

It is correct. If you do not want to use the command line `pdfcpu extract -font` then
you have to call Optimize before you want to do anything with fonts.

The reason: font extraction is an experimental feature only at this point.
Font extraction right now is nothing more than decoding the fontprogram and writing it to disk.
Let me know if there is anything more you need to know.

Thanks for using pdfcpu!

**Comment by miyoyo** [comment]
Oh not really, I'm not using the command line at all, I'm just trying to render the first page of a PDF file, and was extremely frustrated when I posted this.

Unfortunately I still haven't managed to figure out how to extract the content of a page, so I kinda gave up.

It seems that the default font extraction reader bugs out at 32K, using a raw stream fixes it.

The furthest I got was combining this library with https://github.com/ledongthuc/pdf to be able to read the content of the page, but unfortunately it's not able to position images in rects, so until someone either extends it's proto-interpreter for pdf postscript, or finds another way to place images without having to do that, I'll put this on hold and just roll with placeholders.

My font extracting code (to paste them to a file, another library I was using doesn't support io.reader either) was this:
```go
func ExtractFonts(f *pdfcpu.Context) (map[string][]byte, error) {
	d, _, err := f.PageDict(1)
	if err != nil {
		return map[string][]byte{}, fmt.Errorf("Unable to grab page 1")
	}
	o := map[string][]byte{}
	for i, j := range *d.DictEntry("Resources").DictEntry("Font") {
		o[i], err = ExtractFont(f, j)
	}
	return o, nil
}

func ExtractFont(f *pdfcpu.Context, j pdfcpu.Object) ([]byte, error) {
	fontIndirectReference, ok := j.(pdfcpu.IndirectRef)
	if !ok {
		return []byte{}, fmt.Errorf("Unable to convert the font list to an Indirect Reference")
	}
	fontReference, ok := f.FindTableEntryForIndRef(&fontIndirectReference)
	if !ok {
		return []byte{}, fmt.Errorf("Unable to find table entry for the font")
	}
	fontReferenceDict, ok := fontReference.Object.(pdfcpu.Dict)
	if !ok {
		return []byte{}, fmt.Errorf("Unable to convert the font reference to a dict")
	}
	fontDescriptorDirectReference, ok := f.FindTableEntryForIndRef(fontReferenceDict.IndirectRefEntry("FontDescriptor"))
	if !ok {
		return []byte{}, fmt.Errorf("Unable to grab the font descriptor from the font reference")
	}
	fontDescriptorDict, ok := fontDescriptorDirectReference.Object.(pdfcpu.Dict)
	if !ok {
		return []byte{}, fmt.Errorf("Unable to convert the font descriptor reference to a dict")
	}
	name := fontDescriptorDict.NameEntry("FontName")
	if name == nil {
		return []byte{}, fmt.Errorf("Unable to find font name")
	}
	fontFileDirectReference, ok := f.FindTableEntryForIndRef(fontDescriptorDict.IndirectRefEntry("FontFile2"))
	if !ok {
		return []byte{}, fmt.Errorf("Unable to get the font file entry")
	}
	fontStream, err := f.DereferenceStreamDict(fontFileDirectReference.Object)
	if err != nil {
		return []byte{}, fmt.Errorf("Unable to dereference stream")
	}
	return fontStream.Content, nil
}
```

**Comment by hhrutter** [comment]
If you want to convert a PDF page into an image then you need to write a renderer which is basically the foundation of writing a PDF viewer and involves a substantial amount of work.
For that reason I am unable to say if PDF will ever support such a feature.

**Comment by hhrutter** [comment]
OK good luck, there is tons of stuff to consider like page annotations so you're in for a good amount of work.

**Comment by hhrutter** [comment]
this boils down to #45
