### ISSUE TITLE
N-up

### ISSUE THREAD

**Issue by joeky888** [hhrutter/pdfcpu#51]
A pdf file `file.pdf` contains 10 pages, 

I would like to merge these 10 pages into a long single page pdf file `file2.pdf`

It is useful when backing up a webpage or excel files.

As far as I know there is only one tool called `pdfjam` can

do this (by using [N-up](https://en.wikipedia.org/wiki/N-up)) but it is not actively maintained for years,

also `pdfjam` is difficult to install on Windows system.

Any ideas? thanks!

**Comment by hhrutter** [comment]
Hi!

Interesting use case involving
a lot of content stream manipulation.

Definitely doable but unfortunately I am still scratching the surface with
the PDF content syntax.

Something like that gets complex quickly eg. what kind of output do you
expect if the pages you want to concatenate have different page dimensions?

**Comment by joeky888** [comment]
> what kind of output do you
> expect if the pages you want to concatenate have different page dimensions?

Well, I never thought about that before, 

I guess just output some errors to the user instead of brute-force concatenating?

**Comment by hhrutter** [comment]
I do understand the n-Up approach.
eg. using 4-up your 10 pages would end up on 3 pages.
Is this what you are looking for?
Or do you want to turn the 10 pages into one page that has all original pages stacked on top of each other?

**Comment by joeky888** [comment]
> Is this what you are looking for?

Yes.

10-up makes it a long single page pdf file.

**Comment by plaisted** [comment]
> Hi! Interesting use case involving a lot of content stream manipulation.

Ideally you wouldn't have to touch the content streams. Each page would be added to the new N-Up page as an XObject form with the same content stream. The new N-Up content stream would just be positioning the forms correctly. I've never done this so maybe missing something.

**Comment by hhrutter** [comment]
That's correct!
That's actually what I am preparing for the next release.

**Comment by hhrutter** [comment]
Fixed in v0.1.21
