### ISSUE TITLE
Image conversion to PDF using GraphicsMagick

### ISSUE THREAD

**Issue by dhf0820** [hhrutter/pdfcpu#53]
GraphicsMagick generates 1.2 pdf and they fail using pdfcpu with error dereferenceObject: problem dereferencing object 11: parse: corrupt name object.  The files work fine everywhere I have tried them
Do you support back version of pdf?
Don French

**Comment by hhrutter** [comment]
Hello!

pdfcpu works with all PDFs up to V1.7 and should not cause any problem with a V1.2 PDF.

Please attach a sample PDF that you can share and I look into this issue and fix it.
Also please describe the pdfcpu command that gives you the error you mentioned.

Thanks for reporting this!

**Comment by dhf0820** [comment]
I did run it wit a different one that has less PHI on it.  These are converted fromTIFF files with tiff2pdf. I have millions of documents and a small percentage fault.  
[test.log](https://github.com/hhrutter/pdfcpu/files/2659367/test.log)

**Comment by hhrutter** [comment]
Thanks for taking time on this.

This PDF file is using v1.1 which is one of the early versions
and the two dates (CreationDate, ModDate) in the `infodict` do not conform to the spec:

eg `CreationDate, (D:Sat un07105458)` contains an invalid date string
but spec defines dates like: *(D : YYYYMMDDHHmmSSOHH ' mm)*
 
pdfcpu is already relaxing validation for `CreationDate` and will do the same for `ModDate`.

Consider this fixed in the upcoming release.

**Comment by dhf0820** [comment]
Odd it is created by tiff2pdf as the other millions are they all came from the same scanner. If fails if fails on the second page of a two page separate tiff document. I am creating on the fly the multiple tiff pages into a single multi-page pdf document. Not sure how the second page could be bad and the first ok.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by hhrutter** [comment]
On the bright site pdfcpu will soon serve your usecase better. Stay tuned.

**Comment by dhf0820** [comment]
Good. I did figure out a slower workaround. I am first attempting to convert with yours. If that fails I convert the slower way. 

The slower was is 5 times slower. However that is still 10 times faster than imagemagick which was being used. It was taking 50 seconds to convert and combine 30 tiff files. Yours 1.2 seconds.

**Comment by dhf0820** [comment]
I have 6 ways to convert all using ruby. Rmagick is slowest and yours is by far fastest. Second is my personal version then a BIG gap in time to the commonly known ones.

**Comment by hhrutter** [comment]
fixed with v0.1.19
