### ISSUE TITLE
split pdf into n pages

### ISSUE THREAD

**Issue by tcurdt** [hhrutter/pdfcpu#54]
Right now splitting generates a pdf per page.

```
pdfcpu split ~/test.pdf ~/
```

I'd like to split the pdf into 2 pages per split.
I am wondering if I am missing something or whether that's just not supported.

**Comment by hhrutter** [comment]
That's a new usecase.
Right now not supported.

**Comment by tcurdt** [comment]
Would you be OK with supporting it in the future?

I was wondering if I could just re-use the `extract` with the page selection feature.
But that also only supports single page PDF as output. It feels like `split` is special version `extract` at the moment.

I looked at the code but unfortunately it's not that straightforward to add.
The API abstraction is not that flexible in that regard.
Question is whether that's internal and OK to change or whether there are compatibility concerns.

I am also not sure how easy it is to combine n existing pages into one.
I guess `merge` would be the reference there.

**Comment by hhrutter** [comment]
OK I see if I can squeeze this into the next release.

Yes, you could definitely use the merge feature as a workaround in the
meantime.

Am Di., 27. Nov. 2018, 11:51 hat Torsten Curdt <notifications@github.com>
geschrieben:

**Comment by hhrutter** [comment]
Or you could also loop over `Trim` with corresponding `selectedPages` as another workaround.

**Comment by tcurdt** [comment]
Ah, interesting. Feels like there is quite some overlap of `trim`, `extract` and `split`.

**Comment by hhrutter** [comment]
All slightly different usecases.

**Comment by hhrutter** [comment]
fixed with v0.1.19
`Split` has a new `span` parameter.
