### ISSUE TITLE
parse trailer

### ISSUE THREAD

**Issue by rangowang** [hhrutter/pdfcpu#55]
scanTrailerDict() would get error ”unterminated dictionary“ when the trailer content like "trailer
<< /DecodeParms <</Columns 5 /Predictor 12>> /Size 126989 ........ >>.
it only get the truncation "<< /DecodeParms <</Columns 5/Predictor 12>>"....

**Comment by hhrutter** [comment]
If it is possible for you please provide the pdf in question for analysis.
If not please do a pdfcpu validate -vv thefile. pdf &> test.log and provide test.log

Thanks for reporting this!

**Comment by rangowang** [comment]
My PDF32000_2008.pdf trailer is :
trailer
<<
/DecodeParms <<
/Columns 5
/Predictor 12
>>
/Filter /FlateDecode
/ID [<9597C618BC90AFA4A078CA72B2DD061C> <48726007F483D547A8BEFF6E9CDA072F>]
/Info 9 0 R
/Length 137
/Root 1 0 R
/Size 126989
/Type /XRef
/W [1 3 1]
/Index [124332 848]
/Encrypt 126988 0 R
>>
startxref
19951742
%%EOF

but the tailer scanTrailerDict get is“trailer
<<
/DecodeParms <<
/Columns 5
/Predictor 12
>>
“

The stacktrace truncation : “
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: begin
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Object #126984 is in use at offset=19950578, generation=0
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Insert new xreftable entry for Object 126984
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: end
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: begin
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Object #126985 is in use at offset=19950814, generation=0
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Insert new xreftable entry for Object 126985
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: end
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: begin
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Object #126986 is in use at offset=19951046, generation=0
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Insert new xreftable entry for Object 126986
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: end
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: begin
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Object #126987 is in use at offset=19951270, generation=0
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Insert new xreftable entry for Object 126987
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: end
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: begin
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Object #126988 is in use at offset=19951530, generation=0
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: Insert new xreftable entry for Object 126988
DEBUG: 2018/12/03 14:53:10 parseXRefTableEntry: end
DEBUG: 2018/12/03 14:53:10 parseXRefTableSubSection: end
DEBUG: 2018/12/03 14:53:10 parseXRefSection: All subsections read!
DEBUG: 2018/12/03 14:53:10 parseXRefSection: parsing trailer dict..
DEBUG: 2018/12/03 14:53:10 line (len 7) <trailer>
DEBUG: 2018/12/03 14:53:10 parseXRefSection: trailerString: (len:47) <<< /DecodeParms << /Columns 5 /Predictor 12 >> >
Fatal: parse: unterminated dictionary
github.com/hhrutter/pdfcpu/pkg/pdfcpu.init
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/parse.go:38
github.com/hhrutter/pdfcpu/pkg/api.init
        <autogenerated>:1
main.init
        <autogenerated>:1
runtime.main
        C:/Go/src/runtime/proc.go:186
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2361
xRefTable failed
github.com/hhrutter/pdfcpu/pkg/pdfcpu.ReadPDFFile
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/read.go:66
github.com/hhrutter/pdfcpu/pkg/api.Read
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:56
github.com/hhrutter/pdfcpu/pkg/api.Validate
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:75
github.com/hhrutter/pdfcpu/pkg/api.Process
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/pkg/api/process.go:75
main.process
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:251
main.main
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:115
runtime.main
        C:/Go/src/runtime/proc.go:198
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2361
Read failed.
github.com/hhrutter/pdfcpu/pkg/api.Read
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:58
github.com/hhrutter/pdfcpu/pkg/api.Validate
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:75
github.com/hhrutter/pdfcpu/pkg/api.Process
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/pkg/api/process.go:75
main.process
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:251
main.main
        C:/Users/rango/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:115
runtime.main
        C:/Go/src/runtime/proc.go:198
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2361

“
发件人: Horst Rutter<mailto:notifications@github.com>
发送时间: 2018年12月2日 0:24
收件人: hhrutter/pdfcpu<mailto:pdfcpu@noreply.github.com>
抄送: rangowang<mailto:rango.wang@trustasia.com>; Author<mailto:author@noreply.github.com>
主题: Re: [hhrutter/pdfcpu] parse trailer (#55)


I downloaded it and it works for me.

Can you send me the stacktrace you are getting.
Here is how you produce it:
pdfcpu validate -v PDF32000_2008.pdf

Also did you modify this PDF and save it after downloading (possibly using Apple Preview which saves transparently)?

**Comment by hhrutter** [comment]
Are you using the latest commit?
which OS are you on?

**Comment by hhrutter** [comment]
I am going to close this.
The PDF spec file is part of my standard testsuite that I frequently run on darwin/linux64/Win64.
Feel free to reopen if you have smth that can get reproduced in any way.
