### ISSUE TITLE
Remove fmt logs 

### ISSUE THREAD

**Issue by mtham8** [hhrutter/pdfcpu#56]
Hello, 

First of all, great library. Thank you. Thanks for also implementing a Logger interface and the ability to disable logging. However, as I'm trying to split pdf into pages, there are some logs that are actually `fmt`. 

See:
https://github.com/hhrutter/pdfcpu/blob/master/pkg/api/api.go#L316
https://github.com/hhrutter/pdfcpu/blob/master/pkg/api/api.go#L207

Can you update them to use `log` instead? 

Thanks!

**Comment by hhrutter** [comment]
Great input! 
Thanks. 
Sure, will do!

**Comment by hhrutter** [comment]
Fixed with v0.1.19

**Comment by mtham8** [comment]
Thank you for the quick turnaround!
