### ISSUE TITLE
[Enhancement] Allow io.ReadSeeker PDF sources

### ISSUE THREAD

**Issue by plaisted** [hhrutter/pdfcpu#60]
This may be a fringe use-case but it's becoming more common for PDFs to be stored and accessed using object storage such as S3 buckets. In these cases we need to pull file down and cache to disk and the manipulate the PDF (this is true for not just pdfcpu but most products I use). The overhead isn't that big of a deal in most cases but when merging a large number of small documents (100,000++) it starts to add up.

Ideally I'd be able to pass pdfcpu a large list of S3 URLs to merge but allowing the `inFiles` for commands to be `io.ReadSeeker` instead of a filesystem location would allow me to wrap the library as needed for my purposes and allow other file source implementations as well.

I haven't validated if pdfcpu is able to handle merging that many files so there may be other obstacles as well. Using the command line utility we'd run into shell length limits, could have memory problems as well.

**Comment by hhrutter** [comment]
Did you check out `api.ReadContext` and `api.MergeContext` ?
I think there are examples in the [GoDoc](TestMergeUsingReadSeekerCloser).
There is also a testcase in api.process_test.go: `TestMergeUsingReadSeekerCloser`

**Comment by plaisted** [comment]
Not sure how I missed that, looks like what I need. Thank you!
