### ISSUE TITLE
Merging two documents gives me an unterminated dictionary error

### ISSUE THREAD

**Issue by mbinette** [hhrutter/pdfcpu#65]
[d2.pdf](https://github.com/hhrutter/pdfcpu/files/2838086/d2.pdf)
Using v0.1.21 and verbose, I get the following (and the same with pdfcpu validate).

λ pdfcpu merge -v dout.pdf d3.pdf d2.pdf
merging into dout.pdf: [d3.pdf d2.pdf]
 INFO: 2019/02/06 14:58:51 reading d3.pdf..
 INFO: 2019/02/06 14:58:51 PDF Version 1.5 conforming reader
 INFO: 2019/02/06 14:58:51 validating
STATS: 2019/02/06 14:58:51 appendTo: appending d2.pdf to d3.pdf
 INFO: 2019/02/06 14:58:51 reading d2.pdf..
 INFO: 2019/02/06 14:58:51 PDF Version 1.5 conforming reader
Fatal: parse: unterminated dictionary
github.com/hhrutter/pdfcpu/pkg/pdfcpu.init
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/parse.go:33
github.com/hhrutter/pdfcpu/pkg/api.init
        <autogenerated>:1
main.init
        <autogenerated>:1
runtime.main
        C:/Go/src/runtime/proc.go:189
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:1333
decodeObjectStreams: problem decoding object stream 81

github.com/hhrutter/pdfcpu/pkg/pdfcpu.decodeObjectStreams
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/read.go:1804
github.com/hhrutter/pdfcpu/pkg/pdfcpu.dereferenceXRefTable
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/read.go:2068
github.com/hhrutter/pdfcpu/pkg/pdfcpu.Read
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/read.go:85
github.com/hhrutter/pdfcpu/pkg/pdfcpu.ReadFile
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/read.go:57
github.com/hhrutter/pdfcpu/pkg/api.ReadContextFromFile
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:127
github.com/hhrutter/pdfcpu/pkg/api.readAndValidate
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:230
github.com/hhrutter/pdfcpu/pkg/api.appendTo
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:343
github.com/hhrutter/pdfcpu/pkg/api.Merge
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:378
github.com/hhrutter/pdfcpu/pkg/api.Process
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/pkg/api/process.go:75
main.process
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:258
main.main
        D:/dev/fas/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:114
runtime.main
        C:/Go/src/runtime/proc.go:201
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:1333

**Comment by hhrutter** [comment]
Fixed! 
See the latest commit!

You submitted a cornercase where a struct tree uses empty Name objects.
Haven't seen this before but the PDF specification does not explicitly forbid this.

Thanks for reporting this 💚

**Comment by mbinette** [comment]
I tested and it works! Thanks for the quick update.
