### ISSUE TITLE
"Stamp" fails to work for some PDFs

### ISSUE THREAD

**Issue by qjcg** [hhrutter/pdfcpu#67]
I tested the "stamp" functionality of `pdfcpu` and found that it fails to work for some PDF files.

For testing purposes, I used version `0.1.21` of the CLI tool with the following command:

```
pdfcpu stamp TESTING /path/to/file.pdf
```
Below, three examples of "stamp" failures:

Num|PDF|Notes|New PDF created?
------|------|----------|---|
1 |  [PDF ISO 32000-1:2008 specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) | `Read: xRefTable failed: parse: unterminated dictionary` | no
2 | [FDA PDF Guidelines](https://www.fda.gov/downloads/Drugs/DevelopmentApprovalProcess/FormsSubmissionRequirements/ElectronicSubmissions/UCM163565.pdf) | `error: kid not found in parent's kids array` | yes (BUT omits 6 pages from the original!!)
3 | [Canadian Citizenship Study Guide](https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/pub/discover.pdf) | `DereferenceName: invalid <false>` | no

**Comment by hhrutter** [comment]
Did you try the latest commit?
Should at least fix one of these. 
Thanks for taking your time will get right on it

**Comment by qjcg** [comment]
I just built again from latest commit ([be6b07a](https://github.com/hhrutter/pdfcpu/tree/be6b07a8466e7f3e0a02e7803af277cc60d571d4) at time of writing), and I found all 3 errors listed above to be the same unfortunately.

Really appreciate all of your work on this project btw --- pdfcpu is awesome! :)

**Comment by hhrutter** [comment]
thx man. I am on it.

**Comment by hhrutter** [comment]
The latest commit fixes your problems with document 2 and 3.
I had to fix processing of page annotations but doc 1 (the PDF spec) discovered a different bug.
This is an encrypted doc using the empty default password and pdfcpu should be able to process it - yet it does not! I let you know when that's fixed.

Thank you for reporting these bugs!

**Comment by hhrutter** [comment]
Fixed with commit 06789.

**Comment by qjcg** [comment]
Building from the [latest commit](https://github.com/hhrutter/pdfcpu/commit/067897de8ea2ff18ef6a86bf7b2da43f264c0991), I confirm that `stamp` is working now with each of the 3 PDFs mentioned in this issue --- thank you!
