### ISSUE TITLE
Insert blank pages

### ISSUE THREAD

**Issue by sathishvj** [hhrutter/pdfcpu#68]
I want to insert alternate blank pages into the pdf document.  If there are 10 pages, then every alternate page should be blank.  It will help to keep one page of the original document and another where we can take notes.

**Comment by hhrutter** [comment]
Singleside printing gives you one PDF page per papersheet and you could
write on the backside. Would that work for you?

**Comment by sathishvj** [comment]
Actually no for my use case.  These pdfs are on an ipad.  And I have an apple pencil to make notes.

**Comment by hhrutter** [comment]
OK, I put that down as suggested new functionality.

**Comment by hhrutter** [comment]
Fixed with [Version: 0.1.22](https://github.com/hhrutter/pdfcpu/releases/tag/v0.1.22)
