### ISSUE TITLE
Failure to validate/optimize on a particular PDF file

### ISSUE THREAD

**Issue by Mihai-B** [hhrutter/pdfcpu#69]
Hi,
First of all thank you very much for the pdf library, I think this one is one of the most advance library for pdf processing that is out there in GO lang.
However I do have a problem on a particular file that I do not know if I am doing something wrong or I found a small bug, please note that I am very very new to GO, so here it goes:

I have a file that I cannot validate/optimise/extract because it gives an error like this:
`dict=type1FontDict required entry=FirstChar missing`
Now the error seems to be happening because of a missing font? or is it a corrupted pdf file somehow?
Any solution regarding this?

Please note that the exact same file I can open it, and modify it in java with no problem.

**Comment by hhrutter** [comment]
Can you share a test file for analysis? if not please share the output of pdfcpu validate -vv. if relaxed validation chokes we can extend it.

**Comment by Mihai-B** [comment]
@hhrutter I have emailed you a file so you can debug more easily.

**Comment by hhrutter** [comment]
Fixed with latest commit ([967c250](https://github.com/hhrutter/pdfcpu/commit/967c250e0cdf31441df1c79562a00a8df3ab4a52)).
Thanks for reporting this 💚

**Comment by Mihai-B** [comment]
Works perfectly. Thnx for the quick fix
