### ISSUE TITLE
Remove reliance on files as much as possible

### ISSUE THREAD

**Issue by Scapal** [hhrutter/pdfcpu#7]
You should use io.Reader and io.Writer as much as possible to make your library usable in multiple scenarios.

Also for extraction, leave out the file naming and what to do with the exracted content to the library user.

Here is how I managed to do it for Image extraction:

```go
// PDFImageType describe the image file extension
type PDFImageType string

const (
	// JPG jpeg image
	JPG PDFImageType = ".jpg"
	// JPX jpx image
	JPX PDFImageType = ".jpx"
)

// PDFImage provides the content and image format by its extension
type PDFImage struct {
	Body []byte
	Name string
	Type PDFImageType
}

// ExtractImages extracts images to a channel
func ExtractImages(ctx *types.PDFContext, out chan (PDFImage)) {
	for _, i := range sortIOKeys(ctx.Optimize.ImageObjects) {
		ExtractImage(ctx.Optimize.ImageObjects[i], out)
	}
	close(out)
}

// ExtractImage sends image body, ressource name and type to a channel
func ExtractImage(obj *types.ImageObject, out chan (PDFImage)) {
	imageDict := obj.ImageDict

	fp := imageDict.FilterPipeline

	if fp != nil {
		// Ignore imageMasks
		if im := imageDict.BooleanEntry("ImageMask"); im != nil && *im {
			return
		}

		switch fp[0].Name {
		case "DCTDecode":
			out <- PDFImage{Body: imageDict.Raw, Name: obj.ResourceNamesString(), Type: JPG}
		case "JPXDecode":
			out <- PDFImage{Body: imageDict.Raw, Name: obj.ResourceNamesString(), Type: JPX}
		}
	}
}
```

And then I use it like this:

```go
	var err error
	config := types.NewDefaultConfiguration()
	config.DecodeAllStreams = false

	ctx, err := read.PDFFile("data/somefile.pdf", config)
	if err != nil {
		panic(err)
	}

	err = validate.XRefTable(ctx.XRefTable)
	if err != nil {
		panic(err)
	}

	err = optimize.XRefTable(ctx)
	if err != nil {
		panic(err)
	}

	images := make(chan (pdfextract.PDFImage))
	go pdfextract.ExtractImages(ctx, images)
	for img := range images {
		log.Println(img.Name + string(img.Type))
		// Here you could save the images to files, put them on an object store like S3 or Openstack Swift, resize, crop...
	}
```

**Comment by hhrutter** [comment]
I am aware of this issue and it has high priority. I take it as a reminder.. Too much focus has been on my CLI. Thanks!

**Comment by Scapal** [comment]
For my use case, I would like to be able to stream image objects directly to an object storage, without loading it in memory nor saving it to a temporary file first.
The best approach would be to have a forward only reader in the first place, like SAX is for XML parsing. You can build all the other layers on top of it.

[SAX parsing](https://en.wikipedia.org/wiki/Simple_API_for_XML)

**Comment by hhrutter** [comment]
The processing of extracted data is not within scope of the pdfcpu library.

A layer that writes extracted data (in SAX fashion) to an io.Writer (optionally using channels) may be implemented on top of pdfcpu's API.

I therefore close this issue as being taken care of by the redesigned extraction api of release v0.1.9
