### ISSUE TITLE
Errors when merging files

### ISSUE THREAD

**Issue by otto-md** [hhrutter/pdfcpu#71]
Thanks for writing pdfcpu. Im really looking forward to being able to get rid of external tools like pdftk to merge files.

I have a large number of old files that gives me an error when I try to merge them with a file that I have verified is ok.

Ive attached three samples that seems to cover the common cases:
errdereferenceObject.pdf : `dereferenceObject: problem dereferencing object 12: parse: duplicate key`
errvalidateObject.pdf `validateObjectReferenceDict: missing required entry "Obj"`
errxref.pdf `Read: xRefTable failed: parse: unterminated dictionary`

[errpdfs.zip](https://github.com/hhrutter/pdfcpu/files/3012856/errpdfs.zip)

**Comment by otto-md** [comment]
These files could all be merged without errors with pdftk 2.02.

**Comment by hhrutter** [comment]
Thx for reporting this!
💚

**Comment by otto-md** [comment]
I can confirm that it works. Vielen Dank!
