### ISSUE TITLE
Trim not work

### ISSUE THREAD

**Issue by slavablind91** [hhrutter/pdfcpu#72]
I use `Trim` command through `ReadContext/WriteContext`(like in `TestTrimUsingReadSeekerCloser`) and after `b2c24ae` commit it doesn't trim pages and return full pdf.

**Comment by hhrutter** [comment]
This is fixed with the [latest commit](https://github.com/hhrutter/pdfcpu/commit/80aa62c9dd3076f631a9f903cb7c9779d40fd3db).

Take a look at the updated tests for funcs using ReadSeekerAndWriter at process_test.go.

Thanks for reporting this! 
💚

**Comment by slavablind91** [comment]
@hhrutter thanks for quick fix
