### ISSUE TITLE
Invalid PDF v1.4 document

### ISSUE THREAD

**Issue by mbinette** [hhrutter/pdfcpu#73]
When I use `pdfcpu validate my.pdf` on a document generated by a Xerox WorkCentre 7855 I get the following error:

```
validation error: dict=formStreamDict entry=OC: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
```

In Acrobat this is a PDF 1.4 document. I can't control how WorkCentre exports the PDF. Is there a way to work around this issue?

**Comment by hhrutter** [comment]
Difficult to say w/o having a sample in front of me for analysis. I am guessing we are talking about a scanner? Can you scan a testpage and share this?

**Comment by mbinette** [comment]
So the issue is that they scan with the Xerox which makes a valid 1.4 document but then use Adobe Acrobat to add a watermark. The PDF is still a 1.4 but is now invalid. I've attached the -vv log and the PDF.

[log.txt](https://github.com/hhrutter/pdfcpu/files/3023368/log.txt)
[test14watermark.pdf](https://github.com/hhrutter/pdfcpu/files/3023369/test14watermark.pdf)

**Comment by hhrutter** [comment]
Fixed via extension of relaxed validation with commit [eca8f35](https://github.com/hhrutter/pdfcpu/commit/eca8f35ebe5f99da5862212e050824680f23016f).

Thanks for reporting this! 💚
