### ISSUE TITLE
TIFF Decoding: ccitt: corrupt group4 data

### ISSUE THREAD

**Issue by wolfgang-braun** [hhrutter/pdfcpu#75]
nextMode() throws "ccitt: corrupt group4 data" decoding this valid TIFF file:
[test.tiff.zip](https://github.com/hhrutter/pdfcpu/files/3065399/test.tiff.zip)

**Comment by hhrutter** [comment]
Thanks for submitting this.
I will check it out.

**Comment by wolfgang-braun** [comment]
Thanks :) does https://github.com/golang/image/commit/7e034cad644213bc79b336b52fce73624259aeca#diff-ae3c75c384574914b25cb022d46905f4L22 fix this and is it now part of this package?

**Comment by hhrutter** [comment]
image/ccitt and and the integration into image/tiff is an ongoing effort I am involved with.
I am on it but it may be a little bit early to replace the pdfcpu internal packages ccitt,lzw and tiff.
