### ISSUE TITLE
TIFF BitsPerSample tag: Better default behavior

### ISSUE THREAD

**Issue by wolfgang-braun** [hhrutter/pdfcpu#76]
I've forked golang.org-x-image to implement this change:

```golang
d.features[tBitsPerSample] = []uint{1} // BitsPerSample tag is optional in case the value is 1 - if the tag is missing we assume that the tag value is 1
```

https://github.com/wolfgang-braun/golang.org-x-image/commit/6b0041c359e77950c205cd39cfde0b9a0482d136

Maybe you want to apply it to your repository.

**Comment by hhrutter** [comment]
Yes, definitely makes sense.
The spec says that 1 is the default for bits per sample.
This is also fixed in the latest commit [14e74ba2](https://github.com/hhrutter/pdfcpu/commit/14e74ba2c2ebe2ade2aa4c8506c5e9cec2a5fbd8)

Thanks for taking time on this 💚
