### ISSUE TITLE
Feature ideas

### ISSUE THREAD

**Issue by kskyten** [hhrutter/pdfcpu#79]
Thank you for the library. It looks like an extremely good candidate for implementing some of the ideas outlined here: open-source-ideas/open-source-ideas#46. I'm mainly interested in writing XMP metadata to pdf files, removing unnecessary cruft (e.g javascript) and performing smart annotation/conversion using machine learning. I haven't done much programming in Go, but I'd like to try to implement some of these features.

**Comment by hhrutter** [comment]
Sure! Have fun and let me know how it goes.

Just beware that pdfcpu is still alpha.
I am in the process of getting the API stable and ready for a 1.0 release but we are not there yet.
