### ISSUE TITLE
Leave out the logging management to the API user

### ISSUE THREAD

**Issue by Scapal** [hhrutter/pdfcpu#8]
Take a log interface as parameter instead of forcing them in `init()`. Leave to the lib user on how display or store them.
The interface should match `log.Logger` methods.
Put it in the Context.

**Comment by hhrutter** [comment]
Logging has been on my plate forever and I am not satisfied with the current state. Still I need all the logging because it's essential and handy for debugging validation. What you are saying makes total sense. Thanks for pointing that out.

**Comment by hhrutter** [comment]
taken care of with v0.1.7
