### ISSUE TITLE
Validation error for PDF 1.4 file

### ISSUE THREAD

**Issue by leowmjw** [hhrutter/pdfcpu#80]
Noticed the validate command for PDF 1.4 is failing for the following:
http://www.parlimen.gov.my/files/jindex/pdf/Pertanyaan%20Jawapan%20Bukan%20Lisan%2022019.pdf

Details:
```
$ ~/go/bin/pdfcpu validate  ~/Desktop/Pertanyaan\ Jawapan\ Bukan\ Lisan\ 22019.pdf
validating(mode=relaxed) /Users/mleow/Desktop/Pertanyaan Jawapan Bukan Lisan 22019.pdf ...
validation error: dict=pagesDict entry=Tabs: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7

```

Is this a bug or is their PDF generation (via iText) incorrect?

NOTE: A hexedit of the PDF version to 1.7 passes the validation.  Thanks!

**Comment by hhrutter** [comment]
According to the PDF spec within a page dictionary the `Tabs` entry is optional starting with V1.5:

<img width="1004" alt="Screenshot 2019-04-28 at 23 11 45" src="https://user-images.githubusercontent.com/11322155/56870173-ba0b5480-6a0b-11e9-981c-18781116df31.png">

I don't know why iText produces something like this, but in the real world we have also
other PDF Writers whose results pdfcpu needs to be able to digest at the end of the day,
I will extend relaxed validation to include cases like this one.

Thanks for helping to improve pdfcpu 💚

**Comment by hhrutter** [comment]
I just tried this out using the Test in process_test.go: TestSplitCommand() and it works for me.
I am pushing a new release but this should be unrelated.
