### ISSUE TITLE
Read: xRefTable failed: readXRefTable: unexpected eof: EOF

### ISSUE THREAD

**Issue by volodimyr** [hhrutter/pdfcpu#82]
The error I've got is: 

> Read: xRefTable failed: readXRefTable: unexpected eof: EOF

I try to merge two sample pdf files but get the error above.
The pdfcpu binary I use is for the Darwin arch (GOOS=darwin GOARCH=amd64) I cross-compiled recently (0.1.23 version).

`tools/darwin/64/pdfcpu merge tmp/out.pdf tmp/sample1.pdf tmp/sample2.pdf`

Output:

`merging into tmp/out.pdf: [tmp/sample1.pdf tmp/sample2.pdf]
Read: xRefTable failed: readXRefTable: unexpected eof: EOF`

[sample1.pdf](https://github.com/hhrutter/pdfcpu/files/3171530/sample1.pdf)
[sample2.pdf](https://github.com/hhrutter/pdfcpu/files/3171532/sample2.pdf)

Appreciate any suggestions! Thank you for your attention!

**Comment by hhrutter** [comment]
This file was originally created on DOS and then processed by dos2unix on either Linux or Mac.
Migrating from 2 byte eol to 1 byte eol changes the filesize and corrupts the object definition offsets.
Therefore this file is corrupted.

Since other PDF readers can handle this situation I am going to provide one for pdfcpu as well.
Meanwhile as a workaround you can do:
```
brew install dos2unix
unix2dos sample1.pdf
validating(mode=relaxed) sample1.pdf ...
validation ok
```

Thanks for reporting this & helping to improve pdfcpu 💚

**Comment by volodimyr** [comment]
@hhrutter Makes sense for me. Thank you!
I guess we can close the issue.
How did you actually get that meta of file I provided?

**Comment by hhrutter** [comment]
pdfcpu validate -vv sample1. pdf and a good hexeditor :+1:

**Comment by volodimyr** [comment]
That's awesome, appreciate it, thank a lot!

**Comment by hhrutter** [comment]
This is fixed with commit [86b3445](https://github.com/hhrutter/pdfcpu/commit/86b344515ab4f12e80ea26f3c0e519e28047274f).

**Comment by mclark4386** [comment]
@hhrutter should this work for the api calls as well? Running into the same error while trying to merge pdfs in a minio bucket.

**Comment by hhrutter** [comment]
This should be fixed across the board.

Looks like a different issue.
Please file a seperate issue so we can provide a fix for you.
Thank you for using pdfcpu 💚
