### ISSUE TITLE
Signatures From Adobe Disappear After Merge

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [hhrutter/pdfcpu#84]
I have a document that is signed (autographed) with Adobe Acrobat. When the file is saved and then merged with another PDF, the output PDF are the two documents merged. But the person's signature is gone. 

Odd thing is that when I use Mac preview finder and "Export To PDF" on the Adobe PDF prior to passing it through the Merge function, the signatures are still there. 

Any idea what could be causing this? Seems like a PDF encoding issue on the original Adobe PDF. Any special "pre-check" function I can run on a PDF before merging it, like Optimize?

**Comment by hhrutter** [comment]
There are different ways to include an autograph in a PDF. It may be an inlined image or an annotation.
When you use Mac Preview to export to PDF it rewrites the document adding proprietary annotations and possibly along with that inlining annotations but that's just speculation. If you can provide a sample I am happy to look into this. Thanks for reporting this 💚

**Comment by hhrutter** [comment]
Can you provide a sample file? If not I am going to close this.
