### ISSUE TITLE
pdfcpu split failed via API but succeeds via cmd

### ISSUE THREAD

**Issue by leowmjw** [hhrutter/pdfcpu#87]
Related to #80 . Split works with cmd CLI but fails via API call.

Output via cmd:
```
$ pdfcpu split ./raw/Lisan/JDR12032019.pdf /var/folders/_p/
qk0rf40514b4sgy16r5qyxs40000gn/T/pardocs819115744/raw/splitout/Lisan/JDR12032019/pages
splitting ./raw/Lisan/JDR12032019.pdf into /var/folders/_p/qk0rf40514b4sgy16r5qyxs40000gn/T/pardocs819115744/raw/splitout/Lisan/JDR12032019/pages (span=1)...
writing /var/folders/_p/qk0rf40514b4sgy16r5qyxs40000gn/T/pardocs819115744/raw/splitout/Lisan/JDR12032019/pages/JDR12032019_1.pdf ...
writing /var/folders/_p/qk0rf40514b4sgy16r5qyxs40000gn/T/pardocs819115744/raw/splitout/Lisan/JDR12032019/pages/JDR12032019_2.pdf ...
w
..
```
but when using the API it seems to fail

Am I missing  anything?  Confirmed the  validation is in  Relaxed mode

Output via API:
```
OK; splitting!!
VALIDATION:  relaxed
panic: dict=pagesDict entry=Tabs: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
 [recovered]
	panic: dict=pagesDict entry=Tabs: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
```
Code:
```
	conf := pdfcpu.NewDefaultConfiguration()
        // not needed but just to ensure
	conf.ValidationMode = pdfcpu.ValidationRelaxed

	cmd := papi.SplitCommand(sourcePDFPath,  destPDFDir, 1, conf)
	o, perr := papi.Process(cmd)
	if perr != nil {
		panic(perr)
	}
// Above fails!
```

**Comment by hhrutter** [comment]
just tried this out using the Test in process_test.go: TestSplitCommand() and it works for me.
I am pushing a new release but this should be unrelated.

**Comment by StephanVerbeeck** [comment]
same problem here.
Does not work with any of the PDF's that I can find.
The resulting single page PDF's are only 1Kb and invalid (no PDF viewer can read them)
Looks like all the referred objects are not copied along or worse.
Extract of images works fine but extract of pages does not.

	func testPDF02() {
		config := pdfcpu.NewDefaultConfiguration()
		file := "C:\\Account\\indoc\\Rekeninguittreksels_BE70979980972725_2019-04-05_122814.pdf"
		pages := []string{"1-11"}

		{
			cmd := api.ExtractPagesCommand(file, "C:\\Build\\Account\\testResults", pages, config)
			api.ExtractPages(cmd)
		}
		{
			cmd := api.ExtractImagesCommand(file, "C:\\Build\\Account\\testResults", pages, config)
			api.ExtractImages(cmd)
		}
	}

**Comment by hhrutter** [comment]
If you follow the tests in `process_test.go` everything works fine but I agree it makes more sense to call:

`api.ExtractPages(cmd)` 

instead of 

`api.Process(cmd)`.

This will work in the upcoming release.
