### ISSUE TITLE
Checking the config.OwnerPW before it is set value!

### ISSUE THREAD

**Issue by guanwenbogit** [hhrutter/pdfcpu#88]
I don't think it is right here:
```
func prepareEncryptCommand(config *pdfcpu.Configuration) *api.Command {
       //......
	if config.OwnerPW == "" {
		fmt.Fprintf(os.Stderr, "missing non-empty owner password")
		fmt.Fprintf(os.Stderr, "%s\n\n", usageEncrypt)
		os.Exit(1)
	}
        //......
}
```

checking the config.OwnerPW before it is set where calling the config.OwnerPW setting in the main.go.
However, do you want to check the var "opw" here?

**Comment by hhrutter** [comment]
Correct! I am preparing a fix. 
Thanks for discovering this :green_heart
