### ISSUE TITLE
ValidationModeNone?

### ISSUE THREAD

**Issue by gitskyflux** [hhrutter/pdfcpu#89]
Thanks for this great project!

I have a scenario where I really don't care if validation fails during a split command, and I've found that the split command succeeds even when validation has failed in relaxed mode. While I believe it's ultimately beneficial to continue to improve validation, I was hoping you would consider this suggestion for those of us who would rather rely on a failure to split or extract than a failure to validate.

For example, would it be possible to add a third validation mode, something like ValidationModeNone, that would cause certain commands to bypass the validation stage altogether? The Split() function calls readValidateAndOptimize(), which then calls readAndValidate(). With a new validation mode, maybe it results in a call to a new function readAndOptimize(), combining ReadContextFromFile() and OptimizeContext() while avoiding validation.

**Comment by hhrutter** [comment]
This is something to consider also because of the performance impact of validation.
