### ISSUE TITLE
Question/Feature: Unpacking CSV file from encrypted PDF file using UserPW?

### ISSUE THREAD

**Issue by ekanna** [hhrutter/pdfcpu#9]
Hi @hhrutter ,

I receive bank statement in CSV format. As they can't put a password for CSV file, they embed CSV file inside a PDF file and put a user password for PDF file and send it via email.

My job is to fetch this email and extract PDF file and then unpack CSV file from this pdf and save it to DB.

Currently i follow below steps:

1. Fetch email attachment
2. Decrypt PDF file using qpdf
    ```$ qpdf --decrypt --password=myUserPassword inputPdfFile decryptedFile```
3. Unpack CSV file using pdftk
     ```$ pdftk decryptedFile unpack_files output folder```
4. Push CSV file to DB

Can i do step 2 & 3 using pdfcpu?

I have tried step2 using pdfCPU but i am getting below error

> Read failed.: ownerpw not ok and insufficient access permissions

I don't have ownerpw as banks won't share it. I have only userpw.
Is it possible to decrypt pdffile without ownerpw like in qpdf where i use just userpw?

Also any plans to support unpack_files option?

Thanks for this wonderful package. I really love it. Currently i am using this for merging pdf files.

**Comment by hhrutter** [comment]
If decryption fails for a file that only has a userpw this is most likely due to pdfcpu's required permissions to process. See crypto.go: printP() and hasNeededPemissions(). Have hasNeededPermissions return true, then any file protected with a user pw will be processed.
If this does not work for you then it's a bug and I am happy to take a look. Can you provide a testfile?

As far as unpacking goes file attachments are not supported as of now.
Still this is solely due to me not having any test file with attachments.
If you can send me a testfile you give me a chance to  implement attachment support.

Thanks for your valuable input.
Please star pdfcpu if you like it and haven't done so.

**Comment by ekanna** [comment]
Hi @hhrutter 
Thanks for your prompt response. 
Please find attached sample pdf file which has a 1234.csv file embedded in it.
[ekanna.pdf](https://github.com/hhrutter/pdfcpu/files/1443453/ekanna.pdf)

You can refer to 
https://www.pdflabs.com/docs/pdftk-man-page/
Look at "attach_files" command for attaching files
And "unpack_files" for extracting files.

I have already starred this repo. Please let me know if you need any other input. 
Thank you.

**Comment by ekanna** [comment]
Hi @hhrutter 
Step: 2 is not working even after i returned true for hasNeededPemissions() function
Waiting for your  

> command line option to control permissions

Thanks

**Comment by hhrutter** [comment]
I am assuming you recompiled with hasNeededPermission() returning true.
If this really does not work for you then run with all loggings turned on and send me the log output and I analyze. (you may need to set debug and info loggers in read/read.go right at the beginning).
The verbose option on the cmdline does NOT turn on all loggers.

**Comment by ekanna** [comment]
Hi @hhrutter 
I have recompiled. It is failing even before calling hasNeededPermission(). It is failing at ValidateOwnerPassword() in crypto. Below is the  log for the same.

Here is the log 

INFO: 2017/11/06 12:34:49 read.go:2012: PDF Version 1.5 conforming reader
INFO: 2017/11/06 12:34:49 xreftable.go:355: EnsureValidFreeList: empty free list.
INFO: 2017/11/06 12:34:49 read.go:1927: Encryption: (12 0 R)
Fatal: ownerpw not ok and insufficient access permissions
github.com/hhrutter/pdfcpu/read.checkForEncryption
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/read/read.go:1980
github.com/hhrutter/pdfcpu/read.dereferenceXRefTable
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/read/read.go:1869
github.com/hhrutter/pdfcpu/read.PDFFile
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/read/read.go:2025
github.com/hhrutter/pdfcpu.Read
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:66
github.com/hhrutter/pdfcpu.readAndValidate
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:183
github.com/hhrutter/pdfcpu.readValidateAndOptimize
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:203
github.com/hhrutter/pdfcpu.Optimize
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:225
github.com/hhrutter/pdfcpu.Process
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/process.go:128
main.main
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:539
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337
Read failed.
github.com/hhrutter/pdfcpu.Read
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:68
github.com/hhrutter/pdfcpu.readAndValidate
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:183
github.com/hhrutter/pdfcpu.readValidateAndOptimize
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:203
github.com/hhrutter/pdfcpu.Optimize
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:225
github.com/hhrutter/pdfcpu.Process
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/process.go:128
main.main
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:539
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337

**Comment by hhrutter** [comment]
It works like this: First it checks the userpw then it looks at permissions.
If permissions are lacking it checks the ownerpw.
If you do not know the ownerpw then the owner pw check must fail. That's ok.
So for me it still looks like you haven't rebuilt pdfcpu with
hasNeededPermission returning true.
Did you try with the latest V0.1.1 ?

**Comment by ekanna** [comment]
I was using v0.1 now i have updated to v0.1.1 but still problem is continuing. It is not calling hasNeededPermissions() function at all.

```go
if (ctx.Decrypt != nil && *ctx.Decrypt) || !crypto.HasNeededPermissions(enc)
```

```go
// HasNeededPermissions returns true if permissions for pdfcpu processing are present.
func HasNeededPermissions(enc *types.Enc) bool {
	fmt.Println("hello ekanna")
	//
	return true

	// see 7.6.3.2

	printP(enc)

	if enc.R >= 3 {
		// needs set bits 10 and 11
		return enc.P&0x0200 > 0 && enc.P&0x0400 > 0
	}

	// R == 2
	// needs set bits 4 and 5
	return enc.P&0x0008 > 0 && enc.P&0x0010 > 0
}
```
I have recompiled.

Here is the log:

INFO: 2017/11/06 16:41:26 read.go:2034: PDF Version 1.5 conforming reader
INFO: 2017/11/06 16:41:26 xreftable.go:355: EnsureValidFreeList: empty free list.
INFO: 2017/11/06 16:41:26 read.go:1939: Encryption: (12 0 R)
ERROR: 2017/11/06 16:41:26 read.go:1997: userpw ok!
Fatal: ownerpw not ok and insufficient access permissions
github.com/hhrutter/pdfcpu/read.checkForEncryption
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/read/read.go:2002
github.com/hhrutter/pdfcpu/read.dereferenceXRefTable
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/read/read.go:1874
github.com/hhrutter/pdfcpu/read.PDFFile
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/read/read.go:2047
github.com/hhrutter/pdfcpu.Read
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:66
github.com/hhrutter/pdfcpu.readAndValidate
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:183
github.com/hhrutter/pdfcpu.readValidateAndOptimize
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:203
github.com/hhrutter/pdfcpu.Optimize
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:225
github.com/hhrutter/pdfcpu.Decrypt
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:270
github.com/hhrutter/pdfcpu.Process
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/process.go:201
main.main
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:536
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337
Read failed.
github.com/hhrutter/pdfcpu.Read
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:68
github.com/hhrutter/pdfcpu.readAndValidate
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:183
github.com/hhrutter/pdfcpu.readValidateAndOptimize
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:203
github.com/hhrutter/pdfcpu.Optimize
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:225
github.com/hhrutter/pdfcpu.Decrypt
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/api.go:270
github.com/hhrutter/pdfcpu.Process
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/process.go:201
main.main
	/Users/koteswara-0347/goplay/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:536
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337

**Comment by hhrutter** [comment]
The only explanation I have is you are using the DECRYPT command.
If you are using "Decrypt" you have to supply both userpw and ownerpw.

**Comment by hhrutter** [comment]
fixed with v0.1.3

**Comment by ekanna** [comment]
> 1. Decrypt PDF file using qpdf
> $ qpdf --decrypt --password=myUserPassword inputPdfFile decryptedFile
> 2. Unpack CSV file using pdftk
> $ pdftk decryptedFile unpack_files outputFolder

Wow! Now i can eliminate pdftk all together!

How to eliminate qpdf also?

How about giving an option to developer/user whether to respect "Owner Password or not" as long as he has "User Password" just like qpdf?

Thanks a lot!

**Comment by hhrutter** [comment]
Hi, with v0.1.5 you should be able to decrypt using the user pw.
Cheers!

**Comment by ekanna** [comment]
@hhrutter Thanks a lot. It is working great! It is THE pdfcpu!
