### ISSUE TITLE
Distribution: go mod tidy needs to be run on v0.2 branch

### ISSUE THREAD

**Issue by doronbehar** [hhrutter/pdfcpu#92]
Hey,

I'm the maintainer of [pdfcpu on NixOS](https://github.com/NixOS/nixpkgs/pull/63552). While trying to upgrade to `v0.2`, I noticed that the build fails for Nix with the error:

```
can't load package: package github.com/hhrutter/pdfcpu: unknown import path "github.com/hhrutter/pdfcpu": cannot find module providing package github.com/hhrutter/pdfcpu
```

I noticed that if I clone the repo and checkout `v0.2`, running `go install` inside the main directory (not `cmd/pdfcpu`) gives the same error. However, running `go install` inside `cmd/pdfcpu` works but it updates `go.mod` and `go.sum` as so (git diff):

```
diff --git i/go.mod w/go.mod
index 07575c4..070b3c6 100644
--- i/go.mod
+++ w/go.mod
@@ -1,3 +1,7 @@
 module github.com/hhrutter/pdfcpu
 
-require github.com/pkg/errors v0.8.1
+require (
+	github.com/hhrutter/upspin v0.0.0-20171222025218-7c4ed6dbfe1a
+	github.com/pkg/errors v0.8.1
+	upspin.io v0.0.0-20190429152748-8fa1bb72e8fd // indirect
+)
diff --git i/go.sum w/go.sum
index f29ab35..43a6962 100644
--- i/go.sum
+++ w/go.sum
@@ -1,2 +1,6 @@
+github.com/hhrutter/upspin v0.0.0-20171222025218-7c4ed6dbfe1a h1:IQ6drQV0HXnevsP3mQdc52rX/0geElFQTLet/qhtDYo=
+github.com/hhrutter/upspin v0.0.0-20171222025218-7c4ed6dbfe1a/go.mod h1:YYUaCXS8DEMLZM6/andJ62WPnH/wzc+tqmLP7Jppdq8=
 github.com/pkg/errors v0.8.1 h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=
 github.com/pkg/errors v0.8.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
+upspin.io v0.0.0-20190429152748-8fa1bb72e8fd h1:QJI2uIRRQTln1WZrA2UNw/KJSZkAx1lXajP0MCL1+yk=
+upspin.io v0.0.0-20190429152748-8fa1bb72e8fd/go.mod h1:4hdXTXkMPXxzbiw/sultoifpccn98hChAFvrU19V2ug=
```

I'm working on a fix for that under our distribution but I was just thinking you would have liked to know about this. In general As `go.mod` is tracked, it should be updated every once in a while right?

**Comment by hhrutter** [comment]
Hey, thanks for reporting this.
pdfcpu does not require upspin.io! Never did.
I will look into this.

**Comment by hhrutter** [comment]
OK, this unwanted dependency did slip into the release. Patch release in the works..
Really, thanks for reporting this!
