### ISSUE TITLE
PDF failing validation and processing

### ISSUE THREAD

**Issue by mtzanidakis** [hhrutter/pdfcpu#95]
Hello again,
trying to watermark another pdf fails with `Cannot apply stamp. Only one watermark/stamp allowed.`.

The PDF in question fails validation (relaxed) and optimization with:
```
DereferenceDict: wrong type pdfcpu.StreamDict <<<
        <BBox, [0.00 0.00 24.00 24.00]>
        <Filter, FlateDecode>
        <Length, 248>
        <Resources, <<
                <ExtGState, <<
                        <GS0, <<
                                <AIS, false>
                                <BM, Normal>
                                <CA, 0.60>
                                <Type, ExtGState>
                                <ca, 0.60>
                        >>>
                >>>
        >>>
        <Subtype, Form>
        <Type, XObject>
>>>
```
I cannot share this file publicly; is it ok to send this one via email, as well?

**Comment by hhrutter** [comment]
Multiple stamping/watermarking is not supported at the moment.

**Comment by mtzanidakis** [comment]
Sure, the part about multiple stamping/watermarking is clear and understood. The problem is that pdfcpu cannot parse the file in question, at all.
Running any pdfcpu command -- even `info` -- fails with the `wrong type pdfcpu.StreamDict` message, mentioned in the previous post. Would you like to check this file?

**Comment by hhrutter** [comment]
I can take a look
