### ISSUE TITLE
ImportImages should take in an array of io.Reader

### ISSUE THREAD

**Issue by lgonzalez-silen** [hhrutter/pdfcpu#96]
`func ImportImages(rs io.ReadSeeker, w io.Writer, imgFiles []string, imp *pdf.Import, conf *pdf.Configuration) error`

takes in `imgFiles []string` which is paths in the filesystem to the images that are being imported.

It should instead take in an array of Readers.

**Comment by hhrutter** [comment]
Yes I am aware. 
pdfcpu is relying on some magic of the image package in order to detect the image file type.
The image file type controls the PDF filter that needs to be applied in order to import an image into the PDF stream. We'll have to look for a workaround.
