### ISSUE TITLE
Consider using more standard Readers for Merge API function

### ISSUE THREAD

**Issue by lgonzalez-silen** [hhrutter/pdfcpu#97]
Currently,

`func Merge(rsc []ReadSeekerCloser, w io.Writer, conf *pdf.Configuration) error`

takes in an array of non-standard interface `ReadSeekerCloser` as input for the files to merge. This means additional effort to integrate into systems that may be working with standard Readers.

You can work around it by creating your own type satisfying the interface, e.g.

`type BytesReadSeekCloser struct{ *bytes.Reader }`
`func (brsc BytesReadSeekCloser) Close() error { return nil }`

but it would be great to be able to plug in without a workaround or additional boilerplate.

Consider testing within the function if Seeker or Closer are implemented for additional processing.

**Comment by hhrutter** [comment]
Hi! Can you tell me a little bit about your usecase?

**Comment by lgonzalez-silen** [comment]
Sure! We fetch files from S3 that we serve to our users. They come in as io.ReadCloser, but we normally convert to `[]byte` before serving. For one particular workflow, it is more efficient for them to get a group of files as one package. Rather than write them all to disk to merge, we would like to be able to do it without extra writes and without coercing into ReadSeekerCloser.

Incidentally, this package can also have images. We call Optimize and ImportImages as needed before Merge.

**Comment by hhrutter** [comment]
pdfcpu needs at least a ReadSeeker for parsing.
The positioned reading is at the core.

Would it help you if the merge api looked like:
`func Merge(rsc []ReadSeeker, w io.Writer, conf *pdf.Configuration) error`

In the case of Merge the ReadSeekerCloser was just a workaround for passing down a slice of interface values if I recall correctly, mainly a technical issue. There may be a different way to solve this and using ReadSeeker like in the rest of the api will help keeping consistency.

**Comment by lgonzalez-silen** [comment]
Using io.ReadSeeker would be preferable, yes. Makes sense that you need the position, although if it cannot be avoided, it means streaming possibilities are limited.

If io.Closer is useful, you can always type assert .(io.Closer) and do the extra Close call.

**Comment by lgonzalez-silen** [comment]
You are awesome! Thanks!!
